### PR TITLE
Define all response schemas

### PR DESCRIPTION
**Pull request by sbu-WBT**
I defined all schemas from the docs.

Some of the property descriptions are not very descriptive which type it is (in my opinion). So I set the type to object. If you got any ideas which type they are, feel free to comment and I will change them accordingly.

### CODE REVIEW

**Comment by sbu-WBT** [comment]
Any opinions @geoDavey ?

**Comment by 1papaya** [comment]
Hey @sbu-WBT! Just gave the schema the look over and it looks great! Thanks so much for contributing!

**Comment by SimonIT** [comment]
Thanks, I'm gonna define also some more endpoints

**Comment by 1papaya** [comment]
💪💪

**Pull request merged**
